import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/aboutusone">AboutUsOne</Link>
        </li>
        <li>
          <Link to="/">SlideOne</Link>
        </li>
        <li>
          <Link to="/slidetwo">SlideTwo</Link>
        </li>
        <li>
          <Link to="/slidethree">SlideThree</Link>
        </li>
        <li>
          <Link to="/sermonsvariant1">SermonsVariant1</Link>
        </li>
        <li>
          <Link to="/meetourexcos">MeetOurExcos</Link>
        </li>
        <li>
          <Link to="/aboutustwo">AboutUsTwo</Link>
        </li>
        <li>
          <Link to="/aboutusthree">AboutUsThree</Link>
        </li>
        <li>
          <Link to="/sermonsvariant2">SermonsVariant2</Link>
        </li>
        <li>
          <Link to="/aboutusfive">AboutUsFive</Link>
        </li>
        <li>
          <Link to="/aboutusfour">AboutUsFour</Link>
        </li>
        <li>
          <Link to="/sermonsvariant2one">SermonsVariant2One</Link>
        </li>
        <li>
          <Link to="/slideeight">SlideEight</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
